services:
  webserver:
    image: nginx:latest
    container_name: guests-webserver
    working_dir: /application
    ports:
      - "8080:80"
    volumes:
      - ./api:/application
      - ./docker/nginx/nginx-api.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
    networks:
      - app-network

  php-fpm:
    build: docker/php-fpm
    container_name: guests-php-fpm
    volumes:
      - ./api:/application
    depends_on:
      - db
    networks:
      - app-network

  client:
    image: nginx:latest
    container_name: guests-client
    working_dir: /var/www/client
    volumes:
      - ./client:/var/www/client
      - ./docker/nginx/nginx-client.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"

  db:
    image: postgres:15
    container_name: guests-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: guests-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./docker/pgadmin/servers.json:/pgadmin4/servers.json

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
